### ISSUE TITLE
How to push olm to quay.io

### ISSUE THREAD

**Issue by gyliu513** [IBM/common-service-operator#9]
FYI @horis233 @chenzhiwei @DanielXLee 

We need to enable this in Makefile.

**Comment by DanielXLee** [comment]
@gyliu513 do you mean push CSV package to quay.io?

**Comment by gyliu513** [comment]
@DanielXLee Yes, I found that it has been fixed, thanks!

Fixed by https://github.com/IBM/common-service-operator/pull/15
